const questions = [
    { image: "question1.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question2.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question3.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question4.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question5.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question6.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question7.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question8.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question9.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question10.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question11.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question12.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question13.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question14.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question15.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question1.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question2.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question3.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question4.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question5.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question6.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question7.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question8.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question9.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question10.jpg", answers: ["A", "B", "C", "D"], correct: "B" },
    { image: "question11.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question12.jpg", answers: ["A", "B", "C", "D"], correct: "A" },
    { image: "question13.jpg", answers: ["A", "B", "C", "D"], correct: "C" },
    { image: "question14.jpg", answers: ["A", "B", "C", "D"], correct: "D" },
    { image: "question15.jpg", answers: ["A", "B", "C", "D"], correct: "A" }
    
];